### ISSUE TITLE
Error handling for RCON ban

### ISSUE THREAD

**Issue by EnriqCG** [ToriaTo/node-source-rcon#4]
Hello,

thanks a lot for your work in this library.

I've been messing around with this library a lot in the past hours. There doesn't seem to be any error handling for RCON banning.

CS:GO Console:
`Banning XX.XX.XX.XX for rcon hacking attempts. Addip: "<><><>" was banned by IP "permanently" by "Console"`

Code

```javascript
rcon.authenticate(password).then(function () {
    rcon.execute(command).then(function (response) {
        callback(response);
    }).catch(function (e) { //  CATCH EXECUTE
        console.log(e);
    });
}).catch(function (e) {
    console.log(e); //  CATCH AUTH
});
```

**Comment by ToriaTo** [comment]
Thanks for report!
Sadly srcds never send packet about banned situation :(
but still you can check connection status with 'disconnected' event!

```javascript
rcon.connection.on('disconnected', () => {
    if (!rcon.authenticated) { // Disconnected before get authenticated
        // Server not responded or got banned
        console.log('Oof client got friendzoned');
    }
});

rcon.authenticate(password).then(function () {
    rcon.execute(command).then(function (response) {
        callback(response);
    }).catch(function (e) { //  CATCH EXECUTE
        console.log(e);
    });
}).catch(function (e) {
    console.log(e); //  CATCH AUTH
});
```

**Comment by EnriqCG** [comment]
Didn't know that about SRCDS not sending any packet about it. Thanks for the solution.
